# Generated by Django 5.1.2 on 2024-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diseases',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='<EMAIL>', max_length=254),
        ),
    ]
